name: CI/CD

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
    inputs:
      variables:
        description: Pass variables to configure workflow
        required: true
        type: string

concurrency:
  group: main
  cancel-in-progress: false

permissions: {}

jobs:
  compute-matrix:
    name: Compute matrix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.compute-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/compute-matrix
        id: compute-matrix

  front:
    name: '> @shui/${{ matrix.project }}'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ matrix.environment }}
    needs: compute-matrix
    strategy:
      fail-fast: false
      matrix: ${{ needs.compute-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/load-vars
      - uses: ./.github/actions/front
